---
title: "Drake for KnoxData"
---

This is a presentation by [Brian O'Meara](http://brianomeara.info) for the [KnoxData group](https://www.meetup.com/knoxdata/) on March 19, 2020, on the [drake](https://github.com/ropensci/drake) package for making a workflow in R. Thank you to Josh Rosenberg & Alex Pawlowski for inviting me.

The talk is available [here](https://youtu.be/pA50LQdY7Tk).

<iframe width="560" height="315" src="https://www.youtube.com/embed/pA50LQdY7Tk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

You can see code examples made for this at https://github.com/bomeara/drake_knoxdata; to download everything to your computer, https://github.com/bomeara/drake_knoxdata/archive/master.zip

This also uses

* tidyverse
* rmarkdown
* cowplot
* future

The example uses data downloaded from https://transtats.bts.gov/DL_SelectFields.asp: Flight arrivals and departures for US airports for December, 2019.

## Learning objectives

* Utility of workflows
* How and why to use
  * drake
  * RMarkdown
  * Parametric RMarkdown

## Outline of presentation

* Who am I: http://brianomeara.info. I study evolution by creating and using new methods, often implemented in R. You can see my [github profile](https://github.com/bomeara), too.
* Why drake?
  * Reproducibility: https://github.com/bomeara/ReturnOfTheMinivan analysis for a paper (https://doi.org/10.1002/ajb2.1278)
  * Scalability: Comparing over 1,000 faculty Google Scholar profiles for department 10 year report.
  * Saving time: Tweak something, only things that depend on it need to be updated
* Why RMarkdown?
  * Make reports that can easily be changed with different data
* More info: Free drake book (with videos, too): https://books.ropensci.org/drake/
* The old way: https://github.com/bomeara/drake_knoxdata/blob/master/basic_scripts/flight.R. We call the R packages we need, load the data, make the output.
* A basic drake way: https://github.com/bomeara/drake_knoxdata/blob/master/drake_flight_simple
  * In this directory, open R, then you can do `source("make.R")` to run the plan.
  * You'll see plots being made (but the order might differ from the script only version)
  * `vis_drake_graph(plan)` to see how the plan works
* A more fully featured drake way: https://github.com/bomeara/drake_knoxdata/blob/master/drake_flight_complex
  * In this directory, open R, then you can do `source("make.R")` to run the plan.
  * You'll see plots being made (but the order might differ from the script only version)
  * `vis_drake_graph(plan)` to see how the plan works
  * This uses parametric Rmarkdown
* Output from this: https://bomeara.github.io/drake_knoxdata/airport_overview.html
